server:
  port: 9898
  servlet:
    context-path: /test
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: dev
  flyway:
    enabled: true
    validate-on-migrate: true
    check-location: false
    locations: classpath:db/migration/{vendor},classpath:db/migration/dev-data
    baseline-on-migrate: true
    baseline-version: 1
