logging:
  level:
    root: INFO
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ost?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor},classpath:db/migration/dev-data
    baseline-version: 1.2